name: Test
on:
  push:
    branches:
      - training0
      - training1
jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "Hello from ubuntu-latest"
      - name: List files in the repo
        run: |
          ls ${{ github.workspace }}
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: install dependencies
        working-directory: ./tic-tac-toe-app
        run: npm i
      - name: install playwright dependencies
        working-directory: ./tic-tac-toe-app
        run: npx playwright install
      - name: run e2e tests
        working-directory: ./tic-tac-toe-app
        run: npm run playwright
      - uses: actions/upload-artifact@v2
        with:
          name: e2e-results
          path: ./tic-tac-toe-app/test-results/
